import { Request, Response } from "express";
import { asyncHandler } from "../../../utils/async-handler";
import { sendSuccess } from "../../../utils/api-response";
import { SecurityIncident } from "../../security/security-incident.model";
import { getRuleMetrics } from "../risk.service";

export const getRiskMatrix = asyncHandler(async (req: Request, res: Response) => {
  const { range = "30d" } = req.query as { range?: string };

  const rangeMs = {
    "7d": 7 * 24 * 60 * 60 * 1000,
    "30d": 30 * 24 * 60 * 60 * 1000,
    "90d": 90 * 24 * 60 * 60 * 1000,
  }[range] || 30 * 24 * 60 * 60 * 1000;

  const startDate = new Date(Date.now() - rangeMs);

  const [incidents, ruleMetrics] = await Promise.all([
    SecurityIncident.find({ createdAt: { $gte: startDate } }).sort({ createdAt: -1 }).limit(50),
    getRuleMetrics(rangeMs),
  ]);

  const riskEvents = incidents.map((inc) => ({
    id: inc._id?.toString() || "",
    user: inc.entityName,
    event: inc.title,
    riskScore: inc.riskScore,
    riskLevel: (inc.severity.toUpperCase()) as "LOW" | "MEDIUM" | "HIGH" | "CRITICAL",
    timestamp: inc.createdAt.toISOString(),
    status: inc.status.toUpperCase(),
    signals: inc.signals,
    recommendation: inc.signals?.length > 0
      ? `Review: ${inc.signals.slice(0, 2).join(", ")}`
      : "Review incident and take appropriate action.",
  }));

  const overallPlatformRiskScore = riskEvents.length > 0
    ? Math.round(riskEvents.reduce((s, e) => s + e.riskScore, 0) / riskEvents.length)
    : 10;

  const overallRiskLevel = overallPlatformRiskScore >= 70 ? "HIGH" : overallPlatformRiskScore >= 40 ? "MEDIUM" : "LOW";

  sendSuccess(res, {
    range,
    overallPlatformRiskScore,
    overallRiskLevel,
    riskDistribution: {
      critical: riskEvents.filter((e) => e.riskLevel === "CRITICAL").length,
      high: riskEvents.filter((e) => e.riskLevel === "HIGH").length,
      medium: riskEvents.filter((e) => e.riskLevel === "MEDIUM").length,
      low: riskEvents.filter((e) => e.riskLevel === "LOW").length,
    },
    ruleMetrics,
    disclaimer: "Risk scores are heuristic probability indicators generated by rules engine, NOT definitive fraud determinations.",
    events: riskEvents,
  });
});

// 37b. SUSPICIOUS ORDERS DETECTION