export const PLATFORM_KNOWLEDGE = {
  appName: "ShopNest",
  description: "ShopNest is a multi-vendor marketplace platform in Bangladesh where customers can discover products, compare options, and shop securely with buyer protection.",
  features: {
    aiShoppingAssistant: "AI-powered product discovery and recommendations",
    visualSearch: "Upload a photo to find similar products",
    compareProducts: "Compare specifications, prices, and reviews side by side",
    verifiedSellers: "Every seller is vetted before joining the marketplace",
    escrowProtection: "Payments are held securely until delivery is confirmed",
    deliveryTracking: "Real-time order tracking from checkout to doorstep",
    buyerGuarantee: "7-day hassle-free return policy on eligible items",
    multiVendor: "Thousands of independent sellers in one marketplace",
  },
  customerWorkflows: {
    register: "Sign up at /register with name, email, and password. Verify your email to activate your account.",
    browseProducts: "Browse products at /products or use AI Advisor at /ai-advisor for personalized recommendations.",
    addToCart: "Add products to cart from product pages. View cart at /cart.",
    checkout: "Proceed to checkout at /checkout. Choose payment method (Cash on Delivery, bKash, Nagad, Card via SSLCOMMERZ/Stripe).",
    trackOrder: "Track orders at /orders or /dashboard/user/orders.",
    returnProduct: "Initiate returns from order details page within 7 days of delivery. Eligible items must be in original condition with tags and packaging.",
    becomeSeller: "Apply to become a seller at /become-seller. Requires business info, NID/trade license, and bank/payout details.",
    writeReview: "Leave reviews for delivered products from your orders page.",
    wishlist: "Save products to wishlist from product pages. View at /wishlist.",
    notifications: "Check notifications at /notifications or /dashboard/user/notifications.",
    support: "Create a support ticket from the support page or contact seller-support@shopnest.com for seller issues.",
  },
  paymentMethods: [
    { id: "cod", label: "Cash on Delivery", description: "Pay upon parcel receipt" },
    { id: "bkash", label: "bKash", description: "Mobile banking payment" },
    { id: "nagad", label: "Nagad", description: "Mobile banking payment" },
    { id: "card", label: "Card Payment", description: "Visa, Mastercard, Amex via SSLCOMMERZ" },
    { id: "stripe", label: "Stripe", description: "International card payment" },
  ],
  shippingMethods: [
    { id: "home", label: "Home Delivery", description: "Delivered to your doorstep, 2-3 business days", fee: 120 },
    { id: "hub", label: "ShopNest Hub Pickup", description: "Self-pickup from nearest hub, 1-2 business days", fee: 60 },
  ],
  returnPolicy: {
    windowDays: 7,
    description: "Items can be returned within 7 days of delivery if they are in original condition with all tags, accessories, and packaging intact.",
    requiredEvidence: ["Original unboxing photo/video", "Item in undamaged condition with all tags and accessories", "Packaging box with courier shipping label intact"],
    refundMethods: ["Original Payment Method (bKash / Card / Nagad)", "ShopNest Wallet Balance"],
    processingTime: "3-5 Business Days",
  },
  sellerPayoutMethods: [
    { id: "bank", label: "Bank Account Transfer", description: "Direct BEFTN / NPSB transfer to commercial bank" },
    { id: "bkash", label: "bKash Merchant", description: "Instant mobile wallet disbursement" },
    { id: "nagad", label: "Nagad Wallet", description: "Postal service digital financial payout" },
    { id: "rocket", label: "DBBL Rocket", description: "Direct Rocket wallet settlement" },
  ],
  routes: {
    home: "/",
    products: "/products",
    productDetail: (params: Record<string, string>) => `/products/${params.id}`,
    cart: "/cart",
    wishlist: "/wishlist",
    orders: "/orders",
    orderDetail: (params: Record<string, string>) => `/orders/${params.id}`,
    checkout: "/checkout",
    compare: "/compare",
    stores: "/stores",
    storeDetail: (params: Record<string, string>) => `/stores/${params.id}`,
    notifications: "/notifications",
    aiAdvisor: "/ai-advisor",
    login: "/login",
    register: "/register",
    becomeSeller: "/become-seller",
    support: "/support",
    dashboardUser: "/dashboard/user",
    dashboardUserOrders: "/dashboard/user/orders",
    dashboardUserProfile: "/dashboard/user/profile",
    dashboardUserNotifications: "/dashboard/user/notifications",
  },
  orderStatuses: {
    pending: "Order placed, awaiting processing",
    processing: "Order is being prepared for shipment",
    shipped: "Order has been shipped",
    out_for_delivery: "Order is out for delivery",
    delivered: "Order has been delivered",
    cancelled: "Order has been cancelled",
    returned: "Return request approved",
    refunded: "Refund has been processed",
  },
  support: {
    email: "seller-support@shopnest.com",
    ticketSystem: "Available via support page",
    aiSupportChat: "/customer/features/support/ai-chat",
  },
} as const;

export type PlatformKnowledge = typeof PLATFORM_KNOWLEDGE;
